### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received an instance of Object

### ISSUE THREAD

**Issue by jessgoldq4** [robdonn/storybook-module-federation#4]
I get the aforementioned error during build when using the package, but everything works fine after build. Very weird

```
info @storybook/react v6.5.6
info 
info => Cleaning outputDir: /Users/{name}/Code/{repo}/dist
info => Loading presets
WARN   Failed to load preset: {"type":"presets"} on level 1
ERR! TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received an instance of Object
ERR!     at new NodeError (internal/errors.js:322:7)
ERR!     at validateString (internal/validators.js:124:11)
ERR!     at Module.require (internal/modules/cjs/loader.js:967:3)
ERR!     at require (internal/modules/cjs/helpers.js:101:18)
ERR!     at interopRequireDefault (/Users/jessicagold/Code/platform/mfe/platform-mfe-seed/node_modules/@storybook/core-common/dist/cjs/presets.js:178:16)
ERR!     at getContent (/Users/jessicagold/Code/platform/mfe/platform-mfe-seed/node_modules/@storybook/core-common/dist/cjs/presets.js:194:10)
ERR!     at loadPreset (/Users/jessicagold/Code/platform/mfe/platform-mfe-seed/node_modules/@storybook/core-common/dist/cjs/presets.js:203:20)
ERR!     at /Users/jessicagold/Code/platform/mfe/platform-mfe-seed/node_modules/@storybook/core-common/dist/cjs/presets.js:256:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (/Users/jessicagold/Code/platform/mfe/platform-mfe-seed/node_modules/@storybook/core-common/dist/cjs/presets.js:255:18)
ERR!  TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received an instance of Object
ERR!     at new NodeError (internal/errors.js:322:7)
ERR!     at validateString (internal/validators.js:124:11)
ERR!     at Module.require (internal/modules/cjs/loader.js:967:3)
ERR!     at require (internal/modules/cjs/helpers.js:101:18)
ERR!     at interopRequireDefault (/Users/jessicagold/Code/platform/mfe/platform-mfe-seed/node_modules/@storybook/core-common/dist/cjs/presets.js:178:16)
ERR!     at getContent (/Users/jessicagold/Code/platform/mfe/platform-mfe-seed/node_modules/@storybook/core-common/dist/cjs/presets.js:194:10)
ERR!     at loadPreset (/Users/jessicagold/Code/platform/mfe/platform-mfe-seed/node_modules/@storybook/core-common/dist/cjs/presets.js:203:20)
ERR!     at /Users/jessicagold/Code/platform/mfe/platform-mfe-seed/node_modules/@storybook/core-common/dist/cjs/presets.js:256:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (/Users/jessicagold/Code/platform/mfe/platform-mfe-seed/node_modules/@storybook/core-common/dist/cjs/presets.js:255:18) {
ERR!   code: 'ERR_INVALID_ARG_TYPE'
ERR! }
```

main.js:

```
const path = require("path");

require("dotenv").config({ path: path.join(__dirname, "..", "config", "env", ".env") });

const {
  withStorybookModuleFederation,
} = require('storybook-module-federation');

const moduleFederationConfig = {
  name: 'sample',
  filename: 'remoteEntry.js',
  exposes: {
    './sample': "./src/modules/sampleModule/sampleModule.component",
  },
  shared: {
    "react": {
      requiredVersion: ">=17.0.0",
      strictVersion: true,
      singleton: true,
    },
    "react-dom": {
      requiredVersion: ">=17.0.0",
      strictVersion: true,
      singleton: true,
    },
  },
};
const storybookConfig = {
  stories: ['../src/modules/**/*.stories.tsx', '../src/common/**/*.stories.tsx'],
  addons: ['@storybook/addon-links', '@storybook/addon-essentials', '@storybook/addon-jest'],
  framework: '@storybook/react',
  core: {
    builder: 'webpack5',
  },
};

module.exports = withStorybookModuleFederation(moduleFederationConfig)(
  storybookConfig
);

```

**Comment by jessgoldq4** [comment]
Also dotenv is not working at all. The env var values are not loaded in the build
